name: fcm
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # get state manager
  get: ^4.3.8
  get_storage: ^2.0.3
  #
  rxdart: ^0.27.2
  # firebase core
  firebase_core: ^1.10.0
  firebase_messaging: ^11.1.0
  # local notification
  flutter_local_notifications: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
#  flutter_lints: ^1.0.4

flutter:

  uses-material-design: true
